name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-version: '2.2.34'
      - name: Install dependencies
        run: |
          gem install bundler -v 2.2.34
          bundle _2.2.34_ install
      - name: Build site with Jekyll
        run: bundle exec jekyll build
